### PR TITLE
Add an export command

### PR DESCRIPTION
**Pull request by archgrove**
We're currently deploying Credhub alongside Concourse as our primary CI credential store. It's been largely fantastic - thanks so much. There's one thing we've missed so far, which is export.

The ability to mass-export credentials from Credhub would solve two helpful use-cases for us.

1. Backup; we can export the credentials, and store them in an additional encrypted location for backup purposes. As Concourse has a "disposable" setup philosophy (Pipelines and resources are all stored externally), we would like to not have a specific Postgres backup strategy in place (that, indeed, would not prove robust as the Credhub schema changes over time).
2. Mass update; we have a fair number of credentials in Credhub, and did not always store them at the ideal keys. Mass-moving credentials between paths would be much easier if they could be exported, updated in the export, then re-imported.

To facilitate these scenarios, we've created an `export` command, that mirrors the extant `import` command. By default, it exports all credentials to `stdout` in YAML that is `credhub import` compatible. The CLI flag `-p` can restrict the paths being exported; the flag `-f` will redirect the output directly to a file.

It would be really useful to us if this could be upstreamed. If there are changes in style or approach that might help this, we're happy to make them. All suggestions and feedback are _most_ welcome.

### CODE REVIEW

**Comment by benmoss** [comment]
Thanks @archgrove! Looks good.

**Comment by archgrove** [comment]
@benmoss I probably need to provide the documentation linked to in the flag (https://credhub-api.cfapps.io/#export-credentials). Is that in a repo somewhere I can PR to?

**Comment by benmoss** [comment]
@archgrove nice catch. i think of those as being our API documentation, but we documented import there too, which also isn't really an API feature but just a CLI abstraction. if you want to you can send a PR to https://github.com/cloudfoundry-incubator/credhub-api-site

**Comment by archgrove** [comment]
@benmoss Done; see https://github.com/cloudfoundry-incubator/credhub-api-site/pull/6. Thanks!

**Pull request merged**
