### PR TITLE
First cut at adding UAA SSO

### PR DESCRIPTION
**Pull request by aeijdenberg**
Hi all, we thought it might be useful to be able to login in the same manner as `cf`. This PR allows for:

```bash
credhub login --sso
```

### CODE REVIEW

**Comment by danjahner** [comment]
Hi @aeijdenberg - 

Thanks for the PR. Can you please add tests around this functionality?

**Comment by aeijdenberg** [comment]
Hi @danjahner - have added some tests and input validation. Thanks!

**Comment by dannysullivan** [comment]
Hi @aeijdenberg -

We tried this PR out locally and it looks like it's working - we just have two small quibbles:

1. When the SSO passcode is incorrect, the error message says "The provided username and password combination are incorrect. Please validate your input and retry your request." instead of mentioning that the passcode is incorrect.

2. `credhub login --sso` prints out `get passcode from https://login.system.example.com/passcode`, no matter what the configured UAA is.  Can we either change that to show the configured UAA URL, or make it clearer that we're just showing an example (e.g., "<UAA URL>/passcode").

**Comment by crawsible** [comment]
Hi @aeijdenberg -- any response to @dannysullivan?

**Comment by aeijdenberg** [comment]
Hi @crawsible - sorry to go quiet on this one - we've been tied up on other projects, and are out the holiday break now.

Re (2) - this should print a prompt as returned by UAA - defaulting back to the example.com text if not found (and example.com is an official IANA test domain, see https://tools.ietf.org/html/rfc2606#section-3, so it shouldn't conflict with a real site). I've noticed that our Open Source CloudFoundry installs return a sensible prompt, however PCF installs don't seem to. When I get back to the office I'll plan to dig a bit deeper as to why.

**Comment by crawsible** [comment]
@aeijdenberg Cool, sounds good, and no worries on the delay.

**Comment by aeijdenberg** [comment]
@crawsible - I think the last commit should address your comments.

**Comment by benmoss** [comment]
Looks good to me! Thanks @aeijdenberg.

**Pull request merged**
