### PR TITLE
Adds API for interpolate endpoint

### PR DESCRIPTION
**Pull request by idoru**
Signed-off-by: Sam Coward <scoward@pivotal.io>

### CODE REVIEW

**Comment by crawsible** [comment]
@idoru Would you prefer to push to this PRed branch your additions for mTLS support before we pull it in, or to submit mTLS support as an additional PR?

**Comment by idoru** [comment]
@crawsible thanks for asking! Yes, please hold off; we'll update with mTLS support soon.

**Comment by idoru** [comment]
Hi @crawsible! 

This updated pull request removes the global `InterpolateString` method, which we really introduced to avoid unnecessary calls to `/info` endpoint. We've now solved that problem in #14 so no longer have need for it.

Furthermore, since that function is being removed, this code doesn't really care how the client will be created (for the purposes of using mTLS), so we feel this could be merged by itself.

We'll make a seperate pull request soon to add mTLS support.

**Comment by ebeer** [comment]
👍

**Pull request merged**
