### PR TITLE
Extract API calls into a separate package 

### PR DESCRIPTION
**Pull request by tanzeeb**
Hi CredHub Team,

In an effort to make integrating with CredHub easier for other Go projects, we have extracted the API calls in the `commands` package into a separate `api` package. 

As an example, a consuming project can do the following to get a secret stored on Credhub:
```
a := api.NewApi(...)
a.Target(...)
a.LoginWithClientCredentials(...)

secret, err := a.GetByPath(...) // secret is a models.CredentialResponse
```

All API calls currently used by the CLI have an equivalent in the `api` package, and the commands have been updated to use them. We have kept most of the existing command logic exactly the same, just moved the API calls to a function in the `api` package. 

Session management is still handled with a `config` object, but its usage is optional. 

All existing unit and acceptance tests have been kept intact, and we've verified that they all pass.

Some open questions:

1. Do you recommend a separate set of tests for the API, or is the existing set of tests in `commands` sufficient?
1. How do you feel about the approach we have taken?

Thanks,
@tanzeeb, @leungandrew, @pivotal-hargun-suri

### CODE REVIEW

**Comment by pivotal-danjahner** [comment]
Thanks, @tanzeeb. We'll take a look.

**Comment by tanzeeb** [comment]
Hi Phil,

Thanks for the feedback, we agree with almost all of it. I think the most important first step is to agree on the API signatures.

We'll follow up with a revised proposal, taking into account the following:
* Prefer specific over generic (eg. `SetPassword(string,string)` instead `Set(string, interface{})`)
* Parameter structs instead of excessive function parameters
* Strict separation of models used by the API and those used internally by the CLI

Thanks,
@tanzeeb and @leungandrew

**Comment by pivotal-danjahner** [comment]
@tanzeeb @leungandrew Any progress here or any questions that we can clarify? 

Thanks, 
Dan

**Comment by tanzeeb** [comment]
Closing, new PR: https://github.com/cloudfoundry-incubator/credhub-cli/pull/10

**Pull request closed without merging**
