### PR TITLE
Differentiate between generic and credhub errors when getting credentials

### LINKED ISSUE #71: Client library does not differentiate between generic error and credhub.Error when getting credential
### What version of the credhub server you are using?
2.0.1+

### What version of the credhub cli you are using?
2.0.1+ Go client library

### If you were attempting to accomplish a task, what was it you were attempting to do?
Concourse [allows users to store their credentials at either the pipeline or team level](https://github.com/concourse/concourse/blob/213a6acb3e8dc8e02dccda05157ff4dce2ed0c0f/atc/creds/credhub/credhub.go#L26-L41). It first looks for it at `/.../team/pipeline/foo`, if it is unable to find it it will then look at `/.../team/foo`.

If a get credential fails we would like to be able to figure out if it's due to credhub not being able to find the credential (which is acceptable) or something else (which should throw error)

### What did you expect to happen?
Being able to tell the difference between generic (e.g. network unavailable) and credhub (e.g. credential does not exist) errors

### What was the actual behavior?
Both are returned as a `errors.New(...)`

### Are you interested in fixing this yourself?
yep

### PR DESCRIPTION
**Pull request by chenbh**
fixes #71

### CODE REVIEW

**Comment by chenbh** [comment]
Reopening to make my orgs public

**Comment by martys34** [comment]
Thanks!

**Comment by cirocosta** [comment]
Hi @martys34 ,

Regarding the releases for `credhub-cli`, is there a particular cadence that it follows, .e.g, does it get released with the same version (and also at the same time) as CredHub? 

Thanks!

**Comment by joshzarrabi** [comment]
@cirocosta No, we can release a version of the CLI whenever, is us getting a release out a blocker for you?

**Comment by cirocosta** [comment]
Hi @joshzarrabi , thanks for asking!

Yeah, at this point we're mostly waiting for a tagged version to consume as a dependency 😁 

It'd be great to have one for this 👍 👍  Thank you!

**Comment by joshzarrabi** [comment]
@cirocosta Released, thank you!

**Pull request merged**
