### PR TITLE
optional skip missing parameters

### PR DESCRIPTION
**Pull request by calebwashburn**
- added `-s` flag to allow skipping parameters that don't exist in credhub when doing intepolation.
- query ahead of time to get list of creds to allow only querying for values that exist
- save queries for same path.  Useful when looking for private_key and certificate values from the same path during interpolation.

### CODE REVIEW

**Comment by fcohen26** [comment]
Hi Caleb! Thanks for the pull request. We will prioritize soon.

**Comment by calebwashburn** [comment]
@xchapter7x fyi

**Comment by martys34** [comment]
@calebwashburn We tried merging your commit and noticed one issue. The way the interpolate endpoint works right now, if you pass a prefix, the CLI will _also_ return the interpolated values for absolute paths that are not under that prefix. After merging your commit, this was no longer the case and now only credentials which are under the prefix will be returned.

Example:
```
$ cat file
---
/a/pass1: ((/a/pass1))
/a/myval: ((/a/myval))
/b/pass2: ((/b/pass2))
/b/pass: ((/b/pass))

$ credhub interpolate -f file -p /a
/a/myval: <some-val>
/a/pass1: <some-pass>
/b/pass: <some-pass>
/b/pass2: <some-pass>


$ ./credhub-cli interpolate -f file -p /a -s
/a/myval: <some-val>
/a/pass1: <some-pass>
/b/pass: ((/b/pass))
/b/pass2: ((/b/pass2))
```

We found the line of code which created this issue: https://github.com/cloudfoundry-incubator/credhub-cli/pull/70/files#diff-2d300e6ba6f1d987e01a587b91dd1f4dR74.
This will only check for credentials under the prefix but does not check for credentials not returned y the find by path.

We couldn't think of an ideal solution for this. We thought of finding all credentials but that could be in the order of thousands. We also thought of checking error codes on each GET request and ignoring 404s, but the error codes are not propagated up the call stack, only the messages.

**Comment by calebwashburn** [comment]
@martys34 Fixed this issue with latest commit

**Comment by fredwangwang** [comment]
@calebwashburn thinking about uniformed command line arguments, do we want to change the default behavior of `credhub interpolate` not to panic on missing value, but adding an optional `--var-errs` flag to enforce erroring on missing value?

As a cmd user, I'd like to have a similar experience across different utilities, namely `credhub` and `bosh`.

But I don't have a say on the changes, any thoughts from credhub team @fcohen26?

**Comment by calebwashburn** [comment]
@fredwangwang Like that approach... I'll bump the PR with that flag.

**Comment by mdelillo** [comment]
Hey @calebwashburn, thanks for updating your PR. We'll merge this when we get a chance to take a look at it.

@fredwangwang We would like to make sure the CLI is always backwards compatible, and changing the behavior of `interpolate` would break that.

**Comment by fredwangwang** [comment]
@mdelillo That makes sense. Thanks for the response

**Comment by joshzarrabi** [comment]
We merged this manually! https://github.com/cloudfoundry-incubator/credhub-cli/commit/cf1560f1e4faa6a93af538037a2c30bfe9fb5908.

Thank you!

**Comment by jtarchie** [comment]
Thank you!

**Pull request closed without merging**
